In [1]:
#Its time to get that Estimize Data set in
import pandas as pd
#https://pandas.pydata.org/pandas-docs/stable/10min.html
import numpy as np
import os

path = os.getcwd()
filename = 'releases.052317.csv'

print(path)
#Creat BS df = pd.DataFrame(raw_data, columns = ['first_name', 'last_name', 'age', 'preTestScore', 'postTestScore'])

df = pd.read_csv(path + '/' + filename)
print(path + '/' + filename)

/Users/whs/Documents/Quant/Estimize Core Data.052317
/Users/whs/Documents/Quant/Estimize Core Data.052317/releases.052317.csv

In [2]:
df.head()

,id,instrument_id,sector,industry,ticker,fiscal_year,fiscal_quarter,reports_at,metric,actual,...,estimize_mean,select_mean,estimize_count,wallstreet_mean,estimize_high,estimize_low,wallstreet_high,wallstreet_low,guidance_high,guidance_low
0,124096,895,Energy,Energy Equipment & Services,BWP,2017,1,2017-05-01 10:00:00,revenue,367.000,...,362.46625,362.715133,8.0,359.282,NaN,NaN,368.00,350.92,NaN,NaN
1,129088,2311,Information Technology,Internet Software & Services,GDDY,2017,2,2017-08-02 20:00:00,revenue,NaN,...,540.91000,547.693178,8.0,551.020,552.02,552.02,NaN,NaN,NaN,NaN
2,144902,2865,Consumer Staples,Food Products,SNAK,2016,4,2017-03-30 10:00:00,revenue,63.365,...,66.67250,64.965906,12.0,65.200,73.00,73.00,NaN,NaN,NaN,NaN
3,136623,1582,Industrials,Machinery,LECO,2018,2,2018-07-24 10:00:00,eps,NaN,...,NaN,NaN,NaN,1.040,NaN,NaN,1.09,1.00,NaN,NaN
4,135058,729,Energy,"Oil, Gas & Consumable Fuels",PDCE,2018,1,2018-05-04 10:00:00,eps,NaN,...,0.22000,0.231211,3.0,0.306,NaN,NaN,0.46,0.18,NaN,NaN

In [3]:
df.info()
#is this a lot of fluctuations? 
#Good that we're not null

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 369625 entries, 0 to 369624
Data columns (total 21 columns):
id                 369625 non-null int64
instrument_id      369625 non-null int64
sector             369625 non-null object
industry           369625 non-null object
ticker             369625 non-null object
fiscal_year        369625 non-null int64
fiscal_quarter     369625 non-null int64
reports_at         369625 non-null object
metric             369625 non-null object
actual             336305 non-null float64
metric_id          369625 non-null int64
estimize_mean      169453 non-null float64
select_mean        170220 non-null float64
estimize_count     169414 non-null float64
wallstreet_mean    367759 non-null float64
estimize_high      56799 non-null float64
estimize_low       56799 non-null float64
wallstreet_high    90975 non-null float64
wallstreet_low     90975 non-null float64
guidance_high      0 non-null float64
guidance_low       0 non-null float64
dtypes: float64(11), int64(5), object(5)
memory usage: 59.2+ MB

In [4]:
df.describe()

,id,instrument_id,fiscal_year,fiscal_quarter,actual,metric_id,estimize_mean,select_mean,estimize_count,wallstreet_mean,estimize_high,estimize_low,wallstreet_high,wallstreet_low,guidance_high,guidance_low
count,369625.000000,369625.000000,369625.000000,369625.000000,336305.000000,369625.000000,169453.000000,170220.000000,169414.000000,367759.000000,56799.000000,56799.000000,90975.000000,90975.000000,0.0,0.0
mean,73409.700794,1260.379720,2011.419915,2.517235,872.489454,1.483652,1209.081733,1209.885915,16.520789,883.296751,1311.615197,1311.615197,889.177432,835.974223,NaN,NaN
std,42094.736426,748.052919,5.140417,1.126736,3978.164051,0.499733,5120.312156,5192.276837,34.659778,4040.095946,8523.884073,8523.884073,4074.220416,3811.751533,NaN,NaN
min,1.000000,1.000000,1997.000000,1.000000,-827.350000,1.000000,-8.512222,-8.919575,3.000000,-1037.420000,-7.880000,-7.880000,-113.514000,-135.135000,NaN,NaN
25%,35886.000000,590.000000,2008.000000,1.000000,0.320000,1.000000,0.446611,0.446070,5.000000,0.280000,0.500000,0.500000,0.390000,0.300000,NaN,NaN
50%,74476.000000,1273.000000,2013.000000,3.000000,1.710000,1.000000,2.664545,2.712481,8.000000,1.404000,2.890000,2.890000,1.970000,1.710000,NaN,NaN
75%,110069.000000,1856.000000,2016.000000,4.000000,373.100000,2.000000,552.535000,552.007747,16.000000,365.236000,569.730000,569.730000,400.935000,381.545000,NaN,NaN
max,152773.000000,2965.000000,2019.000000,4.000000,138072.000000,2.000000,149063.050000,216476.811207,1184.000000,144392.580000,908163.000000,908163.000000,135504.000000,132555.700000,NaN,NaN

# Sample Data - UAA Only

In [5]:
#Ok, first we need to break this set down...lets just look at UAA

UAA_df = df[df['ticker'] == 'UAA']
#UAA_df.head()
len(UAA_df)
#218 rows

#Sort by fiscal_year then fiscal quarter

UAA_df.sort_values('fiscal_year')
UAA_df.head()
#len(UAA_df)
#218 rows

,id,instrument_id,sector,industry,ticker,fiscal_year,fiscal_quarter,reports_at,metric,actual,...,estimize_mean,select_mean,estimize_count,wallstreet_mean,estimize_high,estimize_low,wallstreet_high,wallstreet_low,guidance_high,guidance_low
402,12979,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2013,3,2013-10-24 10:00:00,eps,0.17,...,0.173125,0.172862,16.0,0.170,NaN,NaN,NaN,NaN,NaN,NaN
1957,13498,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2015,3,2015-10-22 10:00:00,eps,0.23,...,0.230056,0.229060,177.0,0.220,0.27,0.27,NaN,NaN,NaN,NaN
5352,12716,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2012,2,2012-07-24 10:00:00,revenue,369.47,...,358.357500,358.882142,16.0,358.706,NaN,NaN,NaN,NaN,NaN,NaN
5353,12716,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2012,2,2012-07-24 10:00:00,revenue,369.47,...,358.357500,358.882142,16.0,358.706,368.00,368.00,NaN,NaN,NaN,NaN
5354,12716,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2012,2,2012-07-24 10:00:00,revenue,369.47,...,358.357500,358.882142,16.0,358.706,NaN,NaN,NaN,NaN,NaN,NaN

# Create Target Variable Y - Beat (1) or Miss (0) Projection

In [6]:
#Make a new column called Y, DO ONLY ONCE
UAA_df.insert(1, 'Y', 0)

#df.insert(4, "new_col_name", tmp)
UAA_df.sort_values('fiscal_year')

,id,Y,instrument_id,sector,industry,ticker,fiscal_year,fiscal_quarter,reports_at,metric,...,estimize_mean,select_mean,estimize_count,wallstreet_mean,estimize_high,estimize_low,wallstreet_high,wallstreet_low,guidance_high,guidance_low
10751,12555,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2005,4,2005-12-01 10:00:00,revenue,...,NaN,NaN,NaN,78.930,NaN,NaN,NaN,NaN,NaN,NaN
241607,12555,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2005,4,2005-12-01 10:00:00,eps,...,NaN,NaN,NaN,0.010,NaN,NaN,NaN,NaN,NaN,NaN
190834,12558,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2006,1,2006-03-01 10:00:00,revenue,...,NaN,NaN,NaN,72.960,NaN,NaN,NaN,NaN,NaN,NaN
121044,12558,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2006,1,2006-03-01 10:00:00,eps,...,NaN,NaN,NaN,0.010,NaN,NaN,NaN,NaN,NaN,NaN
165274,12563,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2006,2,2006-06-01 08:00:00,eps,...,NaN,NaN,NaN,0.010,NaN,NaN,NaN,NaN,NaN,NaN
73232,12563,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2006,2,2006-06-01 08:00:00,revenue,...,NaN,NaN,NaN,74.620,NaN,NaN,NaN,NaN,NaN,NaN
222134,12566,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2006,3,2006-09-01 08:00:00,revenue,...,NaN,NaN,NaN,118.820,NaN,NaN,NaN,NaN,NaN,NaN
242614,12568,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2006,4,2006-12-01 10:00:00,revenue,...,NaN,NaN,NaN,125.340,NaN,NaN,NaN,NaN,NaN,NaN
60270,12566,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2006,3,2006-09-01 08:00:00,eps,...,NaN,NaN,NaN,0.040,NaN,NaN,NaN,NaN,NaN,NaN
288349,12568,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2006,4,2006-12-01 10:00:00,eps,...,NaN,NaN,NaN,0.040,NaN,NaN,NaN,NaN,NaN,NaN
309095,12577,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2007,3,2007-09-01 08:00:00,revenue,...,NaN,NaN,NaN,170.970,NaN,NaN,NaN,NaN,NaN,NaN
335691,12574,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2007,2,2007-06-01 08:00:00,eps,...,NaN,NaN,NaN,0.010,NaN,NaN,NaN,NaN,NaN,NaN
197418,12570,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2007,1,2007-03-01 10:00:00,revenue,...,NaN,NaN,NaN,120.350,NaN,NaN,NaN,NaN,NaN,NaN
335778,12570,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2007,1,2007-03-01 10:00:00,eps,...,NaN,NaN,NaN,0.030,NaN,NaN,NaN,NaN,NaN,NaN
124767,12579,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2007,4,2007-12-01 10:00:00,revenue,...,NaN,NaN,NaN,173.640,NaN,NaN,NaN,NaN,NaN,NaN
336042,12574,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2007,2,2007-06-01 08:00:00,revenue,...,NaN,NaN,NaN,105.480,NaN,NaN,NaN,NaN,NaN,NaN
101373,12579,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2007,4,2007-12-01 10:00:00,eps,...,NaN,NaN,NaN,0.040,NaN,NaN,NaN,NaN,NaN,NaN
8339,12577,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2007,3,2007-09-01 08:00:00,eps,...,NaN,NaN,NaN,0.050,NaN,NaN,NaN,NaN,NaN,NaN
309096,12585,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2008,2,2008-06-01 08:00:00,revenue,...,NaN,NaN,NaN,157.680,NaN,NaN,NaN,NaN,NaN,NaN
331710,12585,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2008,2,2008-06-01 08:00:00,eps,...,NaN,NaN,NaN,0.010,NaN,NaN,NaN,NaN,NaN,NaN
158637,12588,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2008,3,2008-10-28 06:55:00,revenue,...,NaN,NaN,NaN,227.250,NaN,NaN,NaN,NaN,NaN,NaN
133756,12593,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2008,4,2009-01-29 06:55:00,eps,...,NaN,NaN,NaN,0.030,NaN,NaN,NaN,NaN,NaN,NaN
111976,12588,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2008,3,2008-10-28 06:55:00,eps,...,NaN,NaN,NaN,0.070,NaN,NaN,NaN,NaN,NaN,NaN
85126,12583,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2008,1,2008-03-01 10:00:00,eps,...,NaN,NaN,NaN,0.010,NaN,NaN,NaN,NaN,NaN,NaN
247247,12583,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2008,1,2008-03-01 10:00:00,revenue,...,NaN,NaN,NaN,153.260,NaN,NaN,NaN,NaN,NaN,NaN
365351,12593,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2008,4,2009-01-29 06:55:00,revenue,...,NaN,NaN,NaN,179.650,NaN,NaN,NaN,NaN,NaN,NaN
46284,12603,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2009,3,2009-10-27 06:55:00,revenue,...,NaN,NaN,NaN,250.050,NaN,NaN,NaN,NaN,NaN,NaN
199205,12596,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2009,1,2009-04-28 06:55:00,eps,...,NaN,NaN,NaN,0.010,NaN,NaN,NaN,NaN,NaN,NaN
104665,12605,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2009,4,2010-01-28 06:55:00,eps,...,NaN,NaN,NaN,0.040,NaN,NaN,NaN,NaN,NaN,NaN
290094,12605,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2009,4,2010-01-28 06:55:00,revenue,...,NaN,NaN,NaN,200.370,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277868,131916,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2017,4,2018-01-30 11:00:00,revenue,...,1546.815600,1510.679884,25.0,1510.510,NaN,NaN,NaN,NaN,NaN,NaN
115823,122711,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2017,1,2017-04-27 10:00:00,eps,...,-0.001288,-0.022072,163.0,-0.039,0.10,0.10,NaN,NaN,NaN,NaN
232622,129498,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2017,3,2017-10-24 10:00:00,eps,...,0.287750,0.272316,40.0,0.257,NaN,NaN,NaN,NaN,NaN,NaN
295167,131916,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2017,4,2018-01-30 11:00:00,revenue,...,1546.815600,1510.679884,25.0,1510.510,NaN,NaN,1569.10,1418.80,NaN,NaN
69615,126275,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2017,2,2017-07-25 10:00:00,eps,...,0.011343,-0.016255,67.0,-0.059,NaN,NaN,NaN,NaN,NaN,NaN
247293,122711,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2017,1,2017-04-27 10:00:00,revenue,...,1165.910793,1117.809235,164.0,1105.936,NaN,NaN,1120.20,1066.90,NaN,NaN
295168,131916,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2017,4,2018-01-30 11:00:00,revenue,...,1546.815600,1510.679884,25.0,1510.510,1747.39,1747.39,NaN,NaN,NaN,NaN
364323,126275,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2017,2,2017-07-25 10:00:00,revenue,...,1180.910308,1093.939378,65.0,1077.879,NaN,NaN,1095.90,1040.90,NaN,NaN
231519,122711,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2017,1,2017-04-27 10:00:00,revenue,...,1165.910793,1117.809235,164.0,1105.936,1423.00,1423.00,NaN,NaN,NaN,NaN
231129,122711,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2017,1,2017-04-27 10:00:00,revenue,...,1165.910793,1117.809235,164.0,1105.936,NaN,NaN,NaN,NaN,NaN,NaN
278115,129498,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2017,3,2017-10-24 10:00:00,revenue,...,1710.225526,1657.537521,38.0,1641.727,NaN,NaN,NaN,NaN,NaN,NaN
86639,126275,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2017,2,2017-07-25 10:00:00,eps,...,0.011343,-0.016255,67.0,-0.059,0.07,0.07,NaN,NaN,NaN,NaN
116517,122711,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2017,1,2017-04-27 10:00:00,eps,...,-0.001288,-0.022072,163.0,-0.039,NaN,NaN,NaN,NaN,NaN,NaN
131224,122711,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2017,1,2017-04-27 10:00:00,eps,...,-0.001288,-0.022072,163.0,-0.039,NaN,NaN,-0.03,-0.06,NaN,NaN
162058,135309,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,1,2018-04-26 10:00:00,revenue,...,1355.784000,1289.061631,5.0,1290.997,NaN,NaN,NaN,NaN,NaN,NaN
287241,136521,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,2,2018-07-24 10:00:00,eps,...,0.002500,-0.057552,4.0,-0.038,NaN,NaN,0.02,-0.06,NaN,NaN
287242,136521,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,2,2018-07-24 10:00:00,eps,...,0.002500,-0.057552,4.0,-0.038,0.03,0.03,NaN,NaN,NaN,NaN
46754,147129,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,3,2018-10-23 10:00:00,eps,...,0.320000,0.289517,3.0,0.275,NaN,NaN,0.32,0.23,NaN,NaN
278151,136521,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,2,2018-07-24 10:00:00,eps,...,0.002500,-0.057552,4.0,-0.038,NaN,NaN,NaN,NaN,NaN,NaN
181403,135309,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,1,2018-04-26 10:00:00,revenue,...,1355.784000,1289.061631,5.0,1290.997,1644.52,1644.52,NaN,NaN,NaN,NaN
47433,147129,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,3,2018-10-23 10:00:00,eps,...,0.320000,0.289517,3.0,0.275,NaN,NaN,NaN,NaN,NaN,NaN
333697,136521,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,2,2018-07-24 10:00:00,revenue,...,1356.060000,1256.594458,3.0,1242.860,1568.58,1568.58,NaN,NaN,NaN,NaN
333692,136521,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,2,2018-07-24 10:00:00,revenue,...,1356.060000,1256.594458,3.0,1242.860,NaN,NaN,1281.00,1206.20,NaN,NaN
47902,147129,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,3,2018-10-23 10:00:00,eps,...,0.320000,0.289517,3.0,0.275,0.39,0.39,NaN,NaN,NaN,NaN
324504,136521,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,2,2018-07-24 10:00:00,revenue,...,1356.060000,1256.594458,3.0,1242.860,NaN,NaN,NaN,NaN,NaN,NaN
250524,135309,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,1,2018-04-26 10:00:00,eps,...,0.013333,-0.003267,6.0,0.010,0.06,0.06,NaN,NaN,NaN,NaN
69633,147129,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,3,2018-10-23 10:00:00,revenue,...,NaN,NaN,NaN,1861.790,NaN,NaN,1964.80,1761.60,NaN,NaN
232139,135309,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,1,2018-04-26 10:00:00,eps,...,0.013333,-0.003267,6.0,0.010,NaN,NaN,NaN,NaN,NaN,NaN
181402,135309,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,1,2018-04-26 10:00:00,revenue,...,1355.784000,1289.061631,5.0,1290.997,NaN,NaN,1338.90,1230.60,NaN,NaN
250522,135309,0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,1,2018-04-26 10:00:00,eps,...,0.013333,-0.003267,6.0,0.010,NaN,NaN,0.05,-0.02,NaN,NaN

In [7]:
#Set Y to 0 or 1; make it categorical
UAA_df['Y'] = np.where(UAA_df['actual']>=UAA_df['wallstreet_mean'], 1, np.nan)
UAA_df.sort_values('id')
#print(UAA_df)

/Applications/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

,id,Y,instrument_id,sector,industry,ticker,fiscal_year,fiscal_quarter,reports_at,metric,...,estimize_mean,select_mean,estimize_count,wallstreet_mean,estimize_high,estimize_low,wallstreet_high,wallstreet_low,guidance_high,guidance_low
10751,12555,1.0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2005,4,2005-12-01 10:00:00,revenue,...,NaN,NaN,NaN,78.930,NaN,NaN,NaN,NaN,NaN,NaN
241607,12555,1.0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2005,4,2005-12-01 10:00:00,eps,...,NaN,NaN,NaN,0.010,NaN,NaN,NaN,NaN,NaN,NaN
190834,12558,1.0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2006,1,2006-03-01 10:00:00,revenue,...,NaN,NaN,NaN,72.960,NaN,NaN,NaN,NaN,NaN,NaN
121044,12558,1.0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2006,1,2006-03-01 10:00:00,eps,...,NaN,NaN,NaN,0.010,NaN,NaN,NaN,NaN,NaN,NaN
165274,12563,1.0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2006,2,2006-06-01 08:00:00,eps,...,NaN,NaN,NaN,0.010,NaN,NaN,NaN,NaN,NaN,NaN
73232,12563,1.0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2006,2,2006-06-01 08:00:00,revenue,...,NaN,NaN,NaN,74.620,NaN,NaN,NaN,NaN,NaN,NaN
222134,12566,1.0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2006,3,2006-09-01 08:00:00,revenue,...,NaN,NaN,NaN,118.820,NaN,NaN,NaN,NaN,NaN,NaN
60270,12566,1.0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2006,3,2006-09-01 08:00:00,eps,...,NaN,NaN,NaN,0.040,NaN,NaN,NaN,NaN,NaN,NaN
242614,12568,1.0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2006,4,2006-12-01 10:00:00,revenue,...,NaN,NaN,NaN,125.340,NaN,NaN,NaN,NaN,NaN,NaN
288349,12568,1.0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2006,4,2006-12-01 10:00:00,eps,...,NaN,NaN,NaN,0.040,NaN,NaN,NaN,NaN,NaN,NaN
197418,12570,1.0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2007,1,2007-03-01 10:00:00,revenue,...,NaN,NaN,NaN,120.350,NaN,NaN,NaN,NaN,NaN,NaN
335778,12570,1.0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2007,1,2007-03-01 10:00:00,eps,...,NaN,NaN,NaN,0.030,NaN,NaN,NaN,NaN,NaN,NaN
335691,12574,1.0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2007,2,2007-06-01 08:00:00,eps,...,NaN,NaN,NaN,0.010,NaN,NaN,NaN,NaN,NaN,NaN
336042,12574,1.0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2007,2,2007-06-01 08:00:00,revenue,...,NaN,NaN,NaN,105.480,NaN,NaN,NaN,NaN,NaN,NaN
8339,12577,1.0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2007,3,2007-09-01 08:00:00,eps,...,NaN,NaN,NaN,0.050,NaN,NaN,NaN,NaN,NaN,NaN
309095,12577,1.0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2007,3,2007-09-01 08:00:00,revenue,...,NaN,NaN,NaN,170.970,NaN,NaN,NaN,NaN,NaN,NaN
101373,12579,1.0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2007,4,2007-12-01 10:00:00,eps,...,NaN,NaN,NaN,0.040,NaN,NaN,NaN,NaN,NaN,NaN
124767,12579,1.0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2007,4,2007-12-01 10:00:00,revenue,...,NaN,NaN,NaN,173.640,NaN,NaN,NaN,NaN,NaN,NaN
85126,12583,1.0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2008,1,2008-03-01 10:00:00,eps,...,NaN,NaN,NaN,0.010,NaN,NaN,NaN,NaN,NaN,NaN
247247,12583,1.0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2008,1,2008-03-01 10:00:00,revenue,...,NaN,NaN,NaN,153.260,NaN,NaN,NaN,NaN,NaN,NaN
331710,12585,1.0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2008,2,2008-06-01 08:00:00,eps,...,NaN,NaN,NaN,0.010,NaN,NaN,NaN,NaN,NaN,NaN
309096,12585,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2008,2,2008-06-01 08:00:00,revenue,...,NaN,NaN,NaN,157.680,NaN,NaN,NaN,NaN,NaN,NaN
111976,12588,1.0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2008,3,2008-10-28 06:55:00,eps,...,NaN,NaN,NaN,0.070,NaN,NaN,NaN,NaN,NaN,NaN
158637,12588,1.0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2008,3,2008-10-28 06:55:00,revenue,...,NaN,NaN,NaN,227.250,NaN,NaN,NaN,NaN,NaN,NaN
133756,12593,1.0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2008,4,2009-01-29 06:55:00,eps,...,NaN,NaN,NaN,0.030,NaN,NaN,NaN,NaN,NaN,NaN
365351,12593,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2008,4,2009-01-29 06:55:00,revenue,...,NaN,NaN,NaN,179.650,NaN,NaN,NaN,NaN,NaN,NaN
199205,12596,1.0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2009,1,2009-04-28 06:55:00,eps,...,NaN,NaN,NaN,0.010,NaN,NaN,NaN,NaN,NaN,NaN
61311,12596,1.0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2009,1,2009-04-28 06:55:00,revenue,...,NaN,NaN,NaN,181.590,NaN,NaN,NaN,NaN,NaN,NaN
299092,12600,1.0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2009,2,2009-07-28 06:55:00,revenue,...,NaN,NaN,NaN,157.900,NaN,NaN,NaN,NaN,NaN,NaN
21350,12600,1.0,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2009,2,2009-07-28 06:55:00,eps,...,NaN,NaN,NaN,0.000,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86639,126275,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2017,2,2017-07-25 10:00:00,eps,...,0.011343,-0.016255,67.0,-0.059,0.07,0.07,NaN,NaN,NaN,NaN
86638,126275,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2017,2,2017-07-25 10:00:00,eps,...,0.011343,-0.016255,67.0,-0.059,NaN,NaN,-0.02,-0.07,NaN,NaN
286929,129498,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2017,3,2017-10-24 10:00:00,revenue,...,1710.225526,1657.537521,38.0,1641.727,NaN,NaN,1677.83,1535.00,NaN,NaN
240482,129498,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2017,3,2017-10-24 10:00:00,eps,...,0.287750,0.272316,40.0,0.257,NaN,NaN,0.29,0.20,NaN,NaN
240483,129498,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2017,3,2017-10-24 10:00:00,eps,...,0.287750,0.272316,40.0,0.257,0.35,0.35,NaN,NaN,NaN,NaN
286927,129498,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2017,3,2017-10-24 10:00:00,revenue,...,1710.225526,1657.537521,38.0,1641.727,1840.27,1840.27,NaN,NaN,NaN,NaN
232622,129498,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2017,3,2017-10-24 10:00:00,eps,...,0.287750,0.272316,40.0,0.257,NaN,NaN,NaN,NaN,NaN,NaN
278115,129498,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2017,3,2017-10-24 10:00:00,revenue,...,1710.225526,1657.537521,38.0,1641.727,NaN,NaN,NaN,NaN,NaN,NaN
277868,131916,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2017,4,2018-01-30 11:00:00,revenue,...,1546.815600,1510.679884,25.0,1510.510,NaN,NaN,NaN,NaN,NaN,NaN
295168,131916,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2017,4,2018-01-30 11:00:00,revenue,...,1546.815600,1510.679884,25.0,1510.510,1747.39,1747.39,NaN,NaN,NaN,NaN
340781,131916,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2017,4,2018-01-30 11:00:00,eps,...,0.236296,0.223144,27.0,0.224,0.32,0.32,NaN,NaN,NaN,NaN
340782,131916,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2017,4,2018-01-30 11:00:00,eps,...,0.236296,0.223144,27.0,0.224,NaN,NaN,0.26,0.19,NaN,NaN
324132,131916,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2017,4,2018-01-30 11:00:00,eps,...,0.236296,0.223144,27.0,0.224,NaN,NaN,NaN,NaN,NaN,NaN
295167,131916,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2017,4,2018-01-30 11:00:00,revenue,...,1546.815600,1510.679884,25.0,1510.510,NaN,NaN,1569.10,1418.80,NaN,NaN
162058,135309,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,1,2018-04-26 10:00:00,revenue,...,1355.784000,1289.061631,5.0,1290.997,NaN,NaN,NaN,NaN,NaN,NaN
250524,135309,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,1,2018-04-26 10:00:00,eps,...,0.013333,-0.003267,6.0,0.010,0.06,0.06,NaN,NaN,NaN,NaN
181402,135309,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,1,2018-04-26 10:00:00,revenue,...,1355.784000,1289.061631,5.0,1290.997,NaN,NaN,1338.90,1230.60,NaN,NaN
232139,135309,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,1,2018-04-26 10:00:00,eps,...,0.013333,-0.003267,6.0,0.010,NaN,NaN,NaN,NaN,NaN,NaN
181403,135309,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,1,2018-04-26 10:00:00,revenue,...,1355.784000,1289.061631,5.0,1290.997,1644.52,1644.52,NaN,NaN,NaN,NaN
250522,135309,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,1,2018-04-26 10:00:00,eps,...,0.013333,-0.003267,6.0,0.010,NaN,NaN,0.05,-0.02,NaN,NaN
287242,136521,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,2,2018-07-24 10:00:00,eps,...,0.002500,-0.057552,4.0,-0.038,0.03,0.03,NaN,NaN,NaN,NaN
287241,136521,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,2,2018-07-24 10:00:00,eps,...,0.002500,-0.057552,4.0,-0.038,NaN,NaN,0.02,-0.06,NaN,NaN
333697,136521,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,2,2018-07-24 10:00:00,revenue,...,1356.060000,1256.594458,3.0,1242.860,1568.58,1568.58,NaN,NaN,NaN,NaN
278151,136521,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,2,2018-07-24 10:00:00,eps,...,0.002500,-0.057552,4.0,-0.038,NaN,NaN,NaN,NaN,NaN,NaN
333692,136521,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,2,2018-07-24 10:00:00,revenue,...,1356.060000,1256.594458,3.0,1242.860,NaN,NaN,1281.00,1206.20,NaN,NaN
324504,136521,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,2,2018-07-24 10:00:00,revenue,...,1356.060000,1256.594458,3.0,1242.860,NaN,NaN,NaN,NaN,NaN,NaN
46754,147129,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,3,2018-10-23 10:00:00,eps,...,0.320000,0.289517,3.0,0.275,NaN,NaN,0.32,0.23,NaN,NaN
47433,147129,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,3,2018-10-23 10:00:00,eps,...,0.320000,0.289517,3.0,0.275,NaN,NaN,NaN,NaN,NaN,NaN
47902,147129,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,3,2018-10-23 10:00:00,eps,...,0.320000,0.289517,3.0,0.275,0.39,0.39,NaN,NaN,NaN,NaN
69633,147129,NaN,232,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",UAA,2018,3,2018-10-23 10:00:00,revenue,...,NaN,NaN,NaN,1861.790,NaN,NaN,1964.80,1761.60,NaN,NaN

# Tricky Prep - Isolating and Creating a Feature out EPS and REV

In [14]:
#Now we have to clean up EPS and REV. They are each in the dataset, and we want to makes features out of them

feature_names=('fiscal_year','fiscal_quarter','reports_at','instrument_id',
               'ticker','Y','sector','industry',)
#NOTE: Putting in Y, removes all future data observations

UAA_df1 = UAA_df.pivot_table(index=feature_names,
                     columns='metric', 
                     values='estimize_mean',)
UAA_df1 = UAA_df1.reset_index().rename_axis(None, axis=1)
UAA_df1.rename(columns={'eps': 'EMZ_eps', 'revenue':'EMZ_rev'}, inplace=True)

UAA_df1.info()
UAA_df1.tail()

#Colums that have been remeoved from dataset: 'metric', 'actual', 'metric_id','actual'
#print(UAA_df1)
#print(feature_names)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 10 columns):
fiscal_year       45 non-null int64
fiscal_quarter    45 non-null int64
reports_at        45 non-null object
instrument_id     45 non-null int64
ticker            45 non-null object
Y                 45 non-null float64
sector            45 non-null object
industry          45 non-null object
EMZ_eps           22 non-null float64
EMZ_rev           20 non-null float64
dtypes: float64(3), int64(3), object(4)
memory usage: 3.6+ KB

,fiscal_year,fiscal_quarter,reports_at,instrument_id,ticker,Y,sector,industry,EMZ_eps,EMZ_rev
40,2015,4,2016-01-28 11:00:00,232,UAA,1.0,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",0.239896,1134.592187
41,2016,1,2016-04-21 10:00:00,232,UAA,1.0,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",0.033005,1049.366995
42,2016,2,2016-07-26 10:00:00,232,UAA,1.0,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",0.030185,NaN
43,2016,3,2016-10-25 10:00:00,232,UAA,1.0,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",0.259401,1462.704700
44,2017,1,2017-04-27 10:00:00,232,UAA,1.0,Consumer Discretionary,"Textiles, Apparel & Luxury Goods",-0.001288,1165.910793

In [9]:
#Now we have to go through and seperate everything again as we did with Estimize mean
#with all the rest of these guys

#['estimize_mean','select_mean','estimize_count', 'wallstreet_mean','estimize_high',
#'estimize_low','wallstreet_high','wallstreet_low','guidance_high','guidance_low']

# Creating Features

In [ ]:
#Ok, now for the meat, creating features. We already have our first one in there - EPS estimate
#Lets create EPS Score as our first feature: EMZ_EPSf